version: '3.1'

services:
    consignment-cli:
        build:
            context: ./
            dockerfile: ./cmd/consignment-cli/Dockerfile
        environment:
            MICRO_REGISTRY: "mdsn"

    consignment-service:
        build:
            context: ./
            dockerfile: ./consignment-service/Dockerfile
        ports:
            - 50051:50051
        environment:
            MICRO_ADDRESS: ":50051"
            MICRO_REGISTRY: "mdsn"
            DB_HOST: "datastore:27017"
            DB_NAME: "shippy"
            DB_COLLECTION: "consignments"

    vessel-service:
        build:
            context: ./
            dockerfile: ./vessel-service/Dockerfile
        ports:
            - 50052:50051
        environment:
            MICRO_ADDRESS: ":50051"
            MICRO_REGISTRY: "mdsn"
            DB_HOST: "datastore:27017"
            DB_NAME: "shippy"
            DB_COLLECTION: "vessels"

    user-service:
        build:
            context: ./
            dockerfile: ./user-service/Dockerfile
        ports:
            - 50053:50051
        environment:
            MICRO_ADDRESS: ":50051"
            MICRO_REGISTRY: "mdsn"
            DB_NAME: "postgres"
            DB_HOST: "database"
            DB_PORT: "5432"
            DB_USER: "postgres"
            DB_PASSWORD: "postgres"

    mongodb:
        image: mongo
        ports:
            - 27017:27017

    postgresdb:
        image: postgres
        ports:
            - 5432:5432
